-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role USER-DEFINED NOT NULL DEFAULT 'athlete'::user_role,
  full_name text,
  email text,
  phone text,
  avatar_url text,
  academy_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  preferred_academy_id uuid,
  push_token text,
  academy_code_verified boolean NOT NULL DEFAULT false,
  academy_code_deadline timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT profiles_preferred_academy_id_fkey FOREIGN KEY (preferred_academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.academies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  address text,
  city text,
  state text,
  latitude double precision,
  longitude double precision,
  radius_meters integer DEFAULT 200,
  created_by uuid,
  updated_by uuid,
  is_active boolean DEFAULT true,
  attendance_radius_meters integer DEFAULT 500,
  razorpay_key_id text,
  encrypted_razorpay_secret text,
  payu_merchant_key text,
  encrypted_payu_salt text,
  active_gateway text DEFAULT 'razorpay'::text,
  CONSTRAINT academies_pkey PRIMARY KEY (id),
  CONSTRAINT academies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT academies_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.athlete_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  academy_id uuid,
  full_name text,
  date_of_birth date,
  gender text,
  phone text,
  mobile_number text,
  email text,
  city text,
  state text,
  country text,
  is_minor boolean DEFAULT false,
  emergency_contact_name text,
  emergency_contact_relation text,
  emergency_contact_phone text,
  medical_history_details text,
  current_medications text,
  allergies text,
  health_insurance_provider text,
  boxing_stance text,
  dominant_hand text,
  reach_cm numeric,
  weight_kg numeric,
  height_cm numeric,
  experience_level text,
  primary_goal text,
  fight_record text,
  preferred_class_schedule text,
  previous_club text,
  coach_name text,
  verification_status text DEFAULT 'pending'::text,
  onboarding_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT athlete_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT athlete_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT athlete_profiles_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.access_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid,
  granted_by uuid,
  reason text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT access_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT access_overrides_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT access_overrides_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid NOT NULL,
  academy_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  check_in_time timestamp with time zone DEFAULT now(),
  latitude double precision,
  longitude double precision,
  distance_meters integer,
  status text NOT NULL DEFAULT 'present'::text,
  created_at timestamp with time zone DEFAULT now(),
  marked_at timestamp with time zone DEFAULT now(),
  instance_id uuid,
  pitch_id uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT attendance_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT attendance_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.class_schedule_instances(id),
  CONSTRAINT attendance_pitch_id_fkey FOREIGN KEY (pitch_id) REFERENCES public.class_schedule_pitches(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.discount_schemes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  value_type text NOT NULL DEFAULT 'percentage'::text,
  value numeric NOT NULL,
  applies_to text,
  approval_required boolean DEFAULT false,
  is_active boolean DEFAULT true,
  discount_types ARRAY,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_schemes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_schemes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.fee_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  plan_name text NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  billing_cycle USER-DEFINED NOT NULL DEFAULT 'monthly'::billing_cycle,
  accepted_payment_methods ARRAY DEFAULT ARRAY['cash'::text, 'upi'::text, 'bank_transfer'::text, 'online'::text],
  online_gateway_enabled boolean DEFAULT true,
  late_penalty_enabled boolean DEFAULT false,
  penalty_type USER-DEFINED DEFAULT 'percentage'::penalty_type,
  penalty_value numeric DEFAULT 0,
  grace_period_days integer DEFAULT 7,
  reminder_days_before integer DEFAULT 5,
  reminder_days_after ARRAY DEFAULT ARRAY[1, 3, 7],
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  discount_types ARRAY,
  discount_approval_required boolean DEFAULT false,
  updated_by uuid,
  custom_duration_days integer,
  CONSTRAINT fee_plans_pkey PRIMARY KEY (id),
  CONSTRAINT fee_plans_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT fee_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT fee_plans_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.fee_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid,
  fee_plan_id uuid,
  custom_amount numeric,
  discount_type text,
  discount_value numeric DEFAULT 0,
  discount_reason text,
  discount_approved boolean DEFAULT true,
  fee_start_date date DEFAULT CURRENT_DATE,
  billing_cycle_start date DEFAULT CURRENT_DATE,
  assigned_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  assignment_status text DEFAULT 'sent'::text,
  payment_mode text,
  cash_approved_by uuid,
  cash_approved_at timestamp with time zone,
  notes text,
  online_gateway_enabled boolean DEFAULT true,
  is_current boolean NOT NULL DEFAULT true,
  rollover_requested boolean DEFAULT false,
  rollover_approved boolean DEFAULT false,
  rollover_approved_by uuid,
  rollover_approved_at timestamp with time zone,
  rollover_amount numeric DEFAULT 0,
  CONSTRAINT fee_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT fee_assignments_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT fee_assignments_fee_plan_id_fkey FOREIGN KEY (fee_plan_id) REFERENCES public.fee_plans(id),
  CONSTRAINT fee_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id),
  CONSTRAINT fee_assignments_cash_approved_by_fkey FOREIGN KEY (cash_approved_by) REFERENCES public.profiles(id),
  CONSTRAINT fee_assignments_rollover_approved_by_fkey FOREIGN KEY (rollover_approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL UNIQUE,
  academy_id uuid,
  athlete_profile_id uuid,
  fee_assignment_id uuid,
  billing_period text,
  amount_due numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  balance_outstanding numeric DEFAULT 0,
  due_date date,
  status USER-DEFINED DEFAULT 'unpaid'::invoice_status,
  penalty_applied numeric DEFAULT 0,
  is_overdue boolean DEFAULT false,
  days_overdue integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  coupon_id uuid,
  discount_applied numeric DEFAULT 0,
  payu_txnid text UNIQUE,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT invoices_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT invoices_fee_assignment_id_fkey FOREIGN KEY (fee_assignment_id) REFERENCES public.fee_assignments(id),
  CONSTRAINT invoices_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id)
);
CREATE TABLE public.discount_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid NOT NULL,
  discount_scheme_id uuid,
  invoice_id uuid,
  reason text NOT NULL,
  approval_status text DEFAULT 'approved'::text,
  approved_by uuid,
  approved_at timestamp with time zone,
  applied_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_applications_pkey PRIMARY KEY (id),
  CONSTRAINT discount_applications_applied_by_fkey FOREIGN KEY (applied_by) REFERENCES public.profiles(id),
  CONSTRAINT discount_applications_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT discount_applications_discount_scheme_id_fkey FOREIGN KEY (discount_scheme_id) REFERENCES public.discount_schemes(id),
  CONSTRAINT discount_applications_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT discount_applications_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.guardian_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid UNIQUE,
  guardian_name text NOT NULL,
  relationship text,
  phone text,
  email text,
  consent_given boolean DEFAULT false,
  consent_timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guardian_details_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_details_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id)
);
CREATE TABLE public.leave_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  athlete_profile_id uuid NOT NULL,
  leave_date date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_applications_pkey PRIMARY KEY (id),
  CONSTRAINT leave_applications_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT leave_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  is_read boolean DEFAULT false,
  related_entity_id uuid,
  related_entity_type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  athlete_profile_id uuid,
  amount numeric NOT NULL,
  payment_date date DEFAULT CURRENT_DATE,
  payment_mode text DEFAULT 'online'::text,
  transaction_reference text,
  razorpay_payment_id text UNIQUE,
  razorpay_order_id text,
  razorpay_signature text,
  recorded_by uuid,
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  payment_gateway text DEFAULT 'razorpay'::text CHECK (payment_gateway = ANY (ARRAY['razorpay'::text, 'payu'::text, 'cash'::text, 'other'::text])),
  gateway_response jsonb,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id),
  CONSTRAINT payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.system_settings (
  id text NOT NULL DEFAULT 'singleton'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sent_by uuid,
  academy_id uuid,
  poll_date date NOT NULL DEFAULT CURRENT_DATE,
  title text NOT NULL DEFAULT 'Attendance Poll'::text,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_polls_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_polls_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id),
  CONSTRAINT attendance_polls_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.attendance_poll_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  athlete_profile_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['attending'::text, 'not_attending'::text])),
  reason text,
  responded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_poll_responses_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_poll_responses_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.attendance_polls(id),
  CONSTRAINT attendance_poll_responses_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id)
);
CREATE TABLE public.class_assignment_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sent_by uuid,
  template_id text NOT NULL,
  pitch_id text NOT NULL,
  poll_date date NOT NULL DEFAULT CURRENT_DATE,
  title text NOT NULL DEFAULT 'Practice Class Scheduled'::text,
  message text,
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  academy_id uuid,
  CONSTRAINT class_assignment_polls_pkey PRIMARY KEY (id),
  CONSTRAINT class_assignment_polls_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id),
  CONSTRAINT class_assignment_polls_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.class_assignment_poll_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  athlete_profile_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['attending'::text, 'not_attending'::text])),
  reason text,
  responded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_assignment_poll_responses_pkey PRIMARY KEY (id),
  CONSTRAINT class_assignment_poll_responses_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.class_assignment_polls(id),
  CONSTRAINT class_assignment_poll_responses_athlete_profile_id_fkey FOREIGN KEY (athlete_profile_id) REFERENCES public.athlete_profiles(id)
);
CREATE TABLE public.academy_grounds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  latitude numeric,
  longitude numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academy_grounds_pkey PRIMARY KEY (id),
  CONSTRAINT academy_grounds_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.class_schedule_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  name text NOT NULL,
  days_of_week ARRAY NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_schedule_templates_pkey PRIMARY KEY (id),
  CONSTRAINT class_schedule_templates_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT class_schedule_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.class_schedule_pitches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  name text NOT NULL,
  from_time time without time zone NOT NULL,
  to_time time without time zone NOT NULL,
  ground_id uuid,
  custom_location text,
  custom_lat numeric,
  custom_lng numeric,
  batsmen ARRAY NOT NULL DEFAULT '{}'::uuid[],
  bowlers ARRAY NOT NULL DEFAULT '{}'::uuid[],
  extras ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_schedule_pitches_pkey PRIMARY KEY (id),
  CONSTRAINT class_schedule_pitches_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.class_schedule_templates(id),
  CONSTRAINT class_schedule_pitches_ground_id_fkey FOREIGN KEY (ground_id) REFERENCES public.academy_grounds(id)
);
CREATE TABLE public.class_schedule_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  academy_id uuid NOT NULL,
  date date NOT NULL,
  is_cancelled boolean NOT NULL DEFAULT false,
  cancel_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_schedule_instances_pkey PRIMARY KEY (id),
  CONSTRAINT class_schedule_instances_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.class_schedule_templates(id),
  CONSTRAINT class_schedule_instances_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.class_instance_pitch_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  instance_id uuid NOT NULL,
  pitch_id uuid NOT NULL,
  ground_id uuid,
  custom_location text,
  custom_lat numeric,
  custom_lng numeric,
  from_time time without time zone,
  to_time time without time zone,
  batsmen ARRAY,
  bowlers ARRAY,
  extras ARRAY,
  override_reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_instance_pitch_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT class_instance_pitch_overrides_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.class_schedule_instances(id),
  CONSTRAINT class_instance_pitch_overrides_pitch_id_fkey FOREIGN KEY (pitch_id) REFERENCES public.class_schedule_pitches(id),
  CONSTRAINT class_instance_pitch_overrides_ground_id_fkey FOREIGN KEY (ground_id) REFERENCES public.academy_grounds(id),
  CONSTRAINT class_instance_pitch_overrides_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  value_type text NOT NULL DEFAULT 'percentage'::text,
  value numeric NOT NULL,
  valid_fee_plan_ids ARRAY DEFAULT '{}'::uuid[],
  valid_academy_ids ARRAY DEFAULT '{}'::uuid[],
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  uses_count integer NOT NULL DEFAULT 0 CHECK (uses_count >= 0),
  max_uses integer CHECK (max_uses IS NULL OR max_uses > 0),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.academy_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  created_by uuid,
  is_active boolean NOT NULL DEFAULT true,
  uses_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT academy_codes_pkey PRIMARY KEY (id),
  CONSTRAINT academy_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);