-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text,
  address text,
  city text,
  state text,
  latitude double precision,
  longitude double precision,
  attendance_radius_meters integer NOT NULL DEFAULT 200,
  razorpay_key_id text,
  encrypted_razorpay_secret text,
  payu_merchant_key text,
  encrypted_payu_salt text,
  active_gateway text NOT NULL DEFAULT 'razorpay'::text CHECK (active_gateway = ANY (ARRAY['razorpay'::text, 'payu'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text, 'archived'::text, 'deleted'::text])),
  suspended_reason text,
  suspended_at timestamp with time zone,
  suspended_by uuid,
  archived_at timestamp with time zone,
  hard_delete_eligible_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  onboarded_by uuid,
  onboarded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academies_pkey PRIMARY KEY (id),
  CONSTRAINT academies_suspended_by_fkey FOREIGN KEY (suspended_by) REFERENCES auth.users(id),
  CONSTRAINT academies_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users(id),
  CONSTRAINT academies_onboarded_by_fkey FOREIGN KEY (onboarded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.academy_lifecycle_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['created'::text, 'suspended'::text, 'reactivated'::text, 'archived'::text, 'hard_deleted'::text, 'settings_changed'::text, 'superadmin_invited'::text])),
  reason text,
  actor_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academy_lifecycle_events_pkey PRIMARY KEY (id),
  CONSTRAINT academy_lifecycle_events_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT academy_lifecycle_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['boxos_admin'::text, 'superadmin'::text, 'admin'::text, 'coach'::text, 'athlete'::text, 'external_judge'::text])),
  academy_id uuid,
  full_name text,
  email text,
  phone text,
  avatar_url text,
  preferred_academy_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  push_token text,
  academy_code_verified boolean NOT NULL DEFAULT false,
  academy_code_deadline timestamp with time zone,
  judge_scope_tournament_id uuid,
  access_expires_at timestamp with time zone,
  invited_by uuid,
  terms_accepted_at timestamp with time zone,
  terms_version text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT profiles_preferred_academy_id_fkey FOREIGN KEY (preferred_academy_id) REFERENCES public.academies(id),
  CONSTRAINT profiles_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT fk_profiles_judge_scope_tournament FOREIGN KEY (judge_scope_tournament_id) REFERENCES public.ring_schedule_templates(id)
);
CREATE TABLE public.age_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  name text NOT NULL,
  min_age integer NOT NULL,
  max_age integer,
  gender_scope text NOT NULL CHECK (gender_scope = ANY (ARRAY['men'::text, 'women'::text, 'boys'::text, 'girls'::text, 'all'::text])),
  round_count integer NOT NULL DEFAULT 3,
  round_duration_seconds integer NOT NULL DEFAULT 180,
  rest_duration_seconds integer NOT NULL DEFAULT 60,
  max_eight_counts_per_round integer NOT NULL DEFAULT 3,
  max_eight_counts_per_bout integer NOT NULL DEFAULT 4,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT age_categories_pkey PRIMARY KEY (id),
  CONSTRAINT age_categories_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT age_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.weight_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  age_category_id uuid NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['men'::text, 'women'::text, 'boys'::text, 'girls'::text])),
  name text NOT NULL,
  min_kg numeric NOT NULL,
  max_kg numeric,
  glove_oz integer NOT NULL CHECK (glove_oz = ANY (ARRAY[10, 12])),
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weight_categories_pkey PRIMARY KEY (id),
  CONSTRAINT weight_categories_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT weight_categories_age_category_id_fkey FOREIGN KEY (age_category_id) REFERENCES public.age_categories(id),
  CONSTRAINT weight_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.boxer_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  academy_id uuid NOT NULL,
  full_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text, 'Other'::text])),
  nationality text,
  profile_photo_url text,
  phone text,
  email text,
  city text,
  state text,
  country text,
  blood_group text,
  physical_conditions text,
  current_medications text,
  allergies text,
  medical_fitness_declared boolean NOT NULL DEFAULT false,
  is_minor boolean NOT NULL DEFAULT false,
  onboarding_complete boolean NOT NULL DEFAULT false,
  emergency_contact_name text,
  emergency_contact_relation text,
  emergency_contact_phone text,
  primary_physician_details text,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  stance text CHECK (stance = ANY (ARRAY['orthodox'::text, 'southpaw'::text])),
  declared_weight_kg numeric,
  age_category_id uuid,
  weight_category_id uuid,
  reach_cm numeric,
  height_cm numeric,
  national_federation_boxer_id text,
  record_wins integer NOT NULL DEFAULT 0,
  record_losses integer NOT NULL DEFAULT 0,
  record_draws integer NOT NULL DEFAULT 0,
  record_kos integer NOT NULL DEFAULT 0,
  is_suspended boolean NOT NULL DEFAULT false,
  suspension_start_date date,
  suspension_end_date date,
  suspension_reason text,
  suspended_by uuid,
  suspended_at timestamp with time zone,
  reinstated_by uuid,
  reinstated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT boxer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT boxer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT boxer_profiles_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT boxer_profiles_age_category_id_fkey FOREIGN KEY (age_category_id) REFERENCES public.age_categories(id),
  CONSTRAINT boxer_profiles_weight_category_id_fkey FOREIGN KEY (weight_category_id) REFERENCES public.weight_categories(id),
  CONSTRAINT boxer_profiles_suspended_by_fkey FOREIGN KEY (suspended_by) REFERENCES auth.users(id),
  CONSTRAINT boxer_profiles_reinstated_by_fkey FOREIGN KEY (reinstated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.guardian_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boxer_profile_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  relationship text NOT NULL,
  phone text NOT NULL,
  email text,
  consent_given boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guardian_details_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_details_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id)
);
CREATE TABLE public.fee_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  name text NOT NULL,
  amount numeric NOT NULL,
  cycle text NOT NULL CHECK (cycle = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'half_yearly'::text, 'yearly'::text, 'one_time'::text])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_plans_pkey PRIMARY KEY (id),
  CONSTRAINT fee_plans_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT fee_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.fee_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  fee_plan_id uuid NOT NULL,
  assigned_by uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'completed'::text])),
  rollover_of uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT fee_assignments_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT fee_assignments_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT fee_assignments_fee_plan_id_fkey FOREIGN KEY (fee_plan_id) REFERENCES public.fee_plans(id),
  CONSTRAINT fee_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id),
  CONSTRAINT fee_assignments_rollover_of_fkey FOREIGN KEY (rollover_of) REFERENCES public.fee_assignments(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  fee_assignment_id uuid,
  invoice_number text NOT NULL,
  billing_period_start date,
  billing_period_end date,
  amount_due numeric NOT NULL,
  amount_paid numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'unpaid'::text CHECK (status = ANY (ARRAY['unpaid'::text, 'partially_paid'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text, 'pending_approval'::text])),
  due_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT invoices_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT invoices_fee_assignment_id_fkey FOREIGN KEY (fee_assignment_id) REFERENCES public.fee_assignments(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_mode text NOT NULL CHECK (payment_mode = ANY (ARRAY['online'::text, 'cash'::text, 'rollover'::text])),
  gateway text CHECK (gateway = ANY (ARRAY['razorpay'::text, 'payu'::text])),
  gateway_order_id text,
  gateway_payment_id text,
  reference text,
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'refunded'::text])),
  recorded_by uuid,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id),
  CONSTRAINT payments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  code text NOT NULL,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['flat'::text, 'percentage'::text])),
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  valid_from date,
  valid_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT coupons_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.discount_schemes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  name text NOT NULL,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['flat'::text, 'percentage'::text])),
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  reason text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT discount_schemes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_schemes_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT discount_schemes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.discount_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  discount_scheme_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  invoice_id uuid,
  applied_by uuid,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT discount_applications_pkey PRIMARY KEY (id),
  CONSTRAINT discount_applications_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT discount_applications_discount_scheme_id_fkey FOREIGN KEY (discount_scheme_id) REFERENCES public.discount_schemes(id),
  CONSTRAINT discount_applications_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT discount_applications_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT discount_applications_applied_by_fkey FOREIGN KEY (applied_by) REFERENCES auth.users(id)
);
CREATE TABLE public.academy_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  code text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academy_codes_pkey PRIMARY KEY (id),
  CONSTRAINT academy_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT academy_codes_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  ring_session_id uuid,
  session_date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'present'::text CHECK (status = ANY (ARRAY['present'::text, 'absent'::text])),
  checked_in_at timestamp with time zone DEFAULT now(),
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  distance_meters numeric NOT NULL,
  marked_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT attendance_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT attendance_marked_by_fkey FOREIGN KEY (marked_by) REFERENCES auth.users(id),
  CONSTRAINT fk_attendance_ring_session FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id)
);
CREATE TABLE public.leave_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_applications_pkey PRIMARY KEY (id),
  CONSTRAINT leave_applications_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT leave_applications_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT leave_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.attendance_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  ring_session_id uuid,
  sent_by uuid,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_polls_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_polls_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT attendance_polls_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id),
  CONSTRAINT fk_attendance_polls_ring_session FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id)
);
CREATE TABLE public.attendance_poll_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  response text NOT NULL CHECK (response = ANY (ARRAY['attending'::text, 'not_attending'::text])),
  reason text,
  responded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_poll_responses_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_poll_responses_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.attendance_polls(id),
  CONSTRAINT attendance_poll_responses_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id)
);
CREATE TABLE public.academy_rings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  name text NOT NULL,
  address text,
  latitude double precision,
  longitude double precision,
  geofence_meters integer NOT NULL DEFAULT 200,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academy_rings_pkey PRIMARY KEY (id),
  CONSTRAINT academy_rings_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id)
);
CREATE TABLE public.ring_schedule_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  name text NOT NULL,
  template_type text NOT NULL CHECK (template_type = ANY (ARRAY['training'::text, 'tournament'::text])),
  days_of_week ARRAY NOT NULL DEFAULT '{}'::integer[],
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  host_academy_id uuid,
  is_multi_academy boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_schedule_templates_pkey PRIMARY KEY (id),
  CONSTRAINT ring_schedule_templates_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT ring_schedule_templates_host_academy_id_fkey FOREIGN KEY (host_academy_id) REFERENCES public.academies(id),
  CONSTRAINT ring_schedule_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ring_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  ring_id uuid,
  name text NOT NULL,
  from_time time without time zone NOT NULL,
  to_time time without time zone NOT NULL,
  custom_location text,
  custom_lat double precision,
  custom_lng double precision,
  age_category_id uuid,
  weight_category_id uuid,
  academy_filter_id uuid,
  assigned_boxer_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT ring_sessions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.ring_schedule_templates(id),
  CONSTRAINT ring_sessions_ring_id_fkey FOREIGN KEY (ring_id) REFERENCES public.academy_rings(id),
  CONSTRAINT ring_sessions_age_category_id_fkey FOREIGN KEY (age_category_id) REFERENCES public.age_categories(id),
  CONSTRAINT ring_sessions_weight_category_id_fkey FOREIGN KEY (weight_category_id) REFERENCES public.weight_categories(id),
  CONSTRAINT ring_sessions_academy_filter_id_fkey FOREIGN KEY (academy_filter_id) REFERENCES public.academies(id)
);
CREATE TABLE public.ring_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  academy_id uuid,
  date date NOT NULL,
  instance_type text NOT NULL DEFAULT 'regular'::text CHECK (instance_type = ANY (ARRAY['regular'::text, 'override'::text])),
  venue_name text,
  venue_lat double precision,
  venue_lng double precision,
  geofence_meters integer NOT NULL DEFAULT 200,
  is_cancelled boolean NOT NULL DEFAULT false,
  cancel_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_instances_pkey PRIMARY KEY (id),
  CONSTRAINT ring_instances_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT ring_instances_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.ring_schedule_templates(id)
);
CREATE TABLE public.ring_instance_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ring_instance_id uuid NOT NULL,
  ring_session_id uuid,
  location text,
  lat double precision,
  lng double precision,
  from_time time without time zone,
  to_time time without time zone,
  weight_category_id uuid,
  age_category_id uuid,
  assigned_boxer_ids ARRAY DEFAULT '{}'::uuid[],
  reason text,
  edited_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_instance_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT ring_instance_overrides_ring_instance_id_fkey FOREIGN KEY (ring_instance_id) REFERENCES public.ring_instances(id),
  CONSTRAINT ring_instance_overrides_ring_session_id_fkey FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id),
  CONSTRAINT ring_instance_overrides_weight_category_id_fkey FOREIGN KEY (weight_category_id) REFERENCES public.weight_categories(id),
  CONSTRAINT ring_instance_overrides_age_category_id_fkey FOREIGN KEY (age_category_id) REFERENCES public.age_categories(id),
  CONSTRAINT ring_instance_overrides_edited_by_fkey FOREIGN KEY (edited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ring_assignment_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ring_instance_id uuid NOT NULL,
  sent_by uuid,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_assignment_polls_pkey PRIMARY KEY (id),
  CONSTRAINT ring_assignment_polls_ring_instance_id_fkey FOREIGN KEY (ring_instance_id) REFERENCES public.ring_instances(id),
  CONSTRAINT ring_assignment_polls_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ring_assignment_poll_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  response text NOT NULL CHECK (response = ANY (ARRAY['attending'::text, 'not_attending'::text])),
  reason text,
  responded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ring_assignment_poll_responses_pkey PRIMARY KEY (id),
  CONSTRAINT ring_assignment_poll_responses_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.ring_assignment_polls(id),
  CONSTRAINT ring_assignment_poll_responses_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id)
);
CREATE TABLE public.bouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ring_instance_id uuid NOT NULL,
  ring_session_id uuid NOT NULL,
  bout_number integer,
  boxer_red_id uuid NOT NULL,
  boxer_blue_id uuid NOT NULL,
  age_category_id uuid NOT NULL,
  weight_category_id uuid NOT NULL,
  round_count integer NOT NULL,
  round_duration_seconds integer NOT NULL,
  rest_duration_seconds integer NOT NULL,
  judge_count integer NOT NULL CHECK (judge_count >= 1 AND judge_count <= 5),
  bout_kind text NOT NULL CHECK (bout_kind = ANY (ARRAY['training'::text, 'tournament'::text])),
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'weigh_in_confirmed'::text, 'declaration_pending'::text, 'ready'::text, 'in_progress'::text, 'paused'::text, 'completed'::text, 'cancelled'::text, 'walkover'::text])),
  current_round integer NOT NULL DEFAULT 0,
  current_round_state text NOT NULL DEFAULT 'pending'::text CHECK (current_round_state = ANY (ARRAY['pending'::text, 'active'::text, 'resting'::text, 'ended'::text])),
  red_declared_weight_kg numeric,
  blue_declared_weight_kg numeric,
  weigh_in_confirmed_by uuid,
  weigh_in_confirmed_at timestamp with time zone,
  coach_id uuid,
  winner_boxer_id uuid,
  decision_type text CHECK (decision_type = ANY (ARRAY['WP'::text, 'RSC'::text, 'RSC-I'::text, 'ABD'::text, 'DSQ'::text, 'DQB'::text, 'KO'::text, 'WO'::text, 'DKO'::text, 'BDSQ'::text])),
  decision_detail jsonb,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  completed_by uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bouts_pkey PRIMARY KEY (id),
  CONSTRAINT bouts_ring_instance_id_fkey FOREIGN KEY (ring_instance_id) REFERENCES public.ring_instances(id),
  CONSTRAINT bouts_ring_session_id_fkey FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id),
  CONSTRAINT bouts_boxer_red_id_fkey FOREIGN KEY (boxer_red_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT bouts_boxer_blue_id_fkey FOREIGN KEY (boxer_blue_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT bouts_age_category_id_fkey FOREIGN KEY (age_category_id) REFERENCES public.age_categories(id),
  CONSTRAINT bouts_weight_category_id_fkey FOREIGN KEY (weight_category_id) REFERENCES public.weight_categories(id),
  CONSTRAINT bouts_weigh_in_confirmed_by_fkey FOREIGN KEY (weigh_in_confirmed_by) REFERENCES auth.users(id),
  CONSTRAINT bouts_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.profiles(id),
  CONSTRAINT bouts_winner_boxer_id_fkey FOREIGN KEY (winner_boxer_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT bouts_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.profiles(id),
  CONSTRAINT bouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bout_rounds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  round_number integer NOT NULL,
  started_at timestamp with time zone,
  paused_at timestamp with time zone,
  resumed_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bout_rounds_pkey PRIMARY KEY (id),
  CONSTRAINT bout_rounds_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id)
);
CREATE TABLE public.bout_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  round_number integer,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['knockdown'::text, 'warning'::text, 'foul'::text, 'low_blow'::text, 'injury_timeout'::text])),
  target_boxer_id uuid,
  description text,
  logged_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bout_events_pkey PRIMARY KEY (id),
  CONSTRAINT bout_events_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id),
  CONSTRAINT bout_events_target_boxer_id_fkey FOREIGN KEY (target_boxer_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT bout_events_logged_by_fkey FOREIGN KEY (logged_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bout_judge_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  judge_profile_id uuid NOT NULL,
  judge_role text NOT NULL DEFAULT 'judge'::text CHECK (judge_role = ANY (ARRAY['judge'::text, 'coach_judge'::text])),
  assigned_by uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bout_judge_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT bout_judge_assignments_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id),
  CONSTRAINT bout_judge_assignments_judge_profile_id_fkey FOREIGN KEY (judge_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT bout_judge_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bout_round_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  round_number integer NOT NULL,
  judge_profile_id uuid NOT NULL,
  red_score integer NOT NULL CHECK (red_score >= 6 AND red_score <= 10),
  blue_score integer NOT NULL CHECK (blue_score >= 6 AND blue_score <= 10),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bout_round_scores_pkey PRIMARY KEY (id),
  CONSTRAINT bout_round_scores_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id),
  CONSTRAINT bout_round_scores_judge_profile_id_fkey FOREIGN KEY (judge_profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bout_judge_totals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  judge_profile_id uuid NOT NULL,
  red_total integer NOT NULL,
  blue_total integer NOT NULL,
  winner_boxer_id uuid,
  tie_broken_by uuid,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bout_judge_totals_pkey PRIMARY KEY (id),
  CONSTRAINT bout_judge_totals_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id),
  CONSTRAINT bout_judge_totals_judge_profile_id_fkey FOREIGN KEY (judge_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT bout_judge_totals_winner_boxer_id_fkey FOREIGN KEY (winner_boxer_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT bout_judge_totals_tie_broken_by_fkey FOREIGN KEY (tie_broken_by) REFERENCES auth.users(id)
);
CREATE TABLE public.boxer_bout_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bout_id uuid NOT NULL,
  boxer_profile_id uuid NOT NULL,
  opponent_id uuid,
  result text NOT NULL CHECK (result = ANY (ARRAY['win'::text, 'loss'::text, 'draw'::text, 'no_contest'::text])),
  decision_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT boxer_bout_history_pkey PRIMARY KEY (id),
  CONSTRAINT boxer_bout_history_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT boxer_bout_history_opponent_id_fkey FOREIGN KEY (opponent_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT boxer_bout_history_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id)
);
CREATE TABLE public.external_judge_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_template_id uuid NOT NULL,
  academy_id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  profile_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'expired'::text, 'revoked'::text])),
  invited_by uuid,
  invited_at timestamp with time zone NOT NULL DEFAULT now(),
  activated_at timestamp with time zone,
  expires_at timestamp with time zone,
  revoked_by uuid,
  revoked_at timestamp with time zone,
  CONSTRAINT external_judge_invites_pkey PRIMARY KEY (id),
  CONSTRAINT external_judge_invites_tournament_template_id_fkey FOREIGN KEY (tournament_template_id) REFERENCES public.ring_schedule_templates(id),
  CONSTRAINT external_judge_invites_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT external_judge_invites_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT external_judge_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT external_judge_invites_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.coach_ring_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coach_profile_id uuid NOT NULL,
  ring_instance_id uuid NOT NULL,
  ring_session_id uuid NOT NULL,
  date date NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT coach_ring_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT coach_ring_assignments_coach_profile_id_fkey FOREIGN KEY (coach_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT coach_ring_assignments_ring_instance_id_fkey FOREIGN KEY (ring_instance_id) REFERENCES public.ring_instances(id),
  CONSTRAINT coach_ring_assignments_ring_session_id_fkey FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id),
  CONSTRAINT coach_ring_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.session_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boxer_profile_id uuid NOT NULL,
  attendance_id uuid,
  bout_id uuid,
  rpe_score integer NOT NULL CHECK (rpe_score >= 0 AND rpe_score <= 10),
  comment text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT session_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT session_feedback_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT session_feedback_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendance(id),
  CONSTRAINT session_feedback_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id)
);
CREATE TABLE public.fitness_test_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  name text NOT NULL,
  unit text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_test_types_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_test_types_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT fitness_test_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.fitness_test_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boxer_profile_id uuid NOT NULL,
  test_type_id uuid NOT NULL,
  value numeric NOT NULL,
  unit_snapshot text NOT NULL,
  recorded_date date NOT NULL,
  recorded_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_test_records_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_test_records_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT fitness_test_records_test_type_id_fkey FOREIGN KEY (test_type_id) REFERENCES public.fitness_test_types(id),
  CONSTRAINT fitness_test_records_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.pregnancy_declarations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boxer_profile_id uuid NOT NULL,
  ring_instance_id uuid NOT NULL,
  ring_session_id uuid NOT NULL,
  bout_id uuid,
  status text NOT NULL DEFAULT 'pending_window'::text CHECK (status = ANY (ARRAY['pending_window'::text, 'open'::text, 'submitted'::text, 'missed'::text])),
  window_opens_at timestamp with time zone NOT NULL,
  submitted_at timestamp with time zone,
  submitted_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pregnancy_declarations_pkey PRIMARY KEY (id),
  CONSTRAINT pregnancy_declarations_boxer_profile_id_fkey FOREIGN KEY (boxer_profile_id) REFERENCES public.boxer_profiles(id),
  CONSTRAINT pregnancy_declarations_ring_instance_id_fkey FOREIGN KEY (ring_instance_id) REFERENCES public.ring_instances(id),
  CONSTRAINT pregnancy_declarations_ring_session_id_fkey FOREIGN KEY (ring_session_id) REFERENCES public.ring_sessions(id),
  CONSTRAINT pregnancy_declarations_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES public.bouts(id),
  CONSTRAINT pregnancy_declarations_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academy_id uuid,
  recipient_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  data jsonb,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_academy_id_fkey FOREIGN KEY (academy_id) REFERENCES public.academies(id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);