/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BoxosAdminRouteImport } from './routes/boxos-admin'
import { Route as AthleteRouteImport } from './routes/athlete'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as JudgeIndexRouteImport } from './routes/judge.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as BoxosAdminIndexRouteImport } from './routes/boxos-admin.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminReportsRouteImport } from './routes/superadmin.reports'
import { Route as SuperadminRefundsRouteImport } from './routes/superadmin.refunds'
import { Route as SuperadminNotificationsRouteImport } from './routes/superadmin.notifications'
import { Route as SuperadminJudgesRouteImport } from './routes/superadmin.judges'
import { Route as SuperadminFeesRouteImport } from './routes/superadmin.fees'
import { Route as SuperadminDiscountsRouteImport } from './routes/superadmin.discounts'
import { Route as SuperadminConfigRouteImport } from './routes/superadmin.config'
import { Route as SuperadminCoachesRouteImport } from './routes/superadmin.coaches'
import { Route as SuperadminClassAssigningRouteImport } from './routes/superadmin.class-assigning'
import { Route as SuperadminBoutsRouteImport } from './routes/superadmin.bouts'
import { Route as SuperadminAttendanceRouteImport } from './routes/superadmin.attendance'
import { Route as SuperadminAthletesRouteImport } from './routes/superadmin.athletes'
import { Route as SuperadminAdminsRouteImport } from './routes/superadmin.admins'
import { Route as SuperadminAcademiesRouteImport } from './routes/superadmin.academies'
import { Route as JudgeExpiredRouteImport } from './routes/judge.expired'
import { Route as CoachSettingsRouteImport } from './routes/coach.settings'
import { Route as CoachNotificationsRouteImport } from './routes/coach.notifications'
import { Route as CoachBoxersRouteImport } from './routes/coach.boxers'
import { Route as CoachAttendanceRouteImport } from './routes/coach.attendance'
import { Route as BoxosAdminSettingsRouteImport } from './routes/boxos-admin.settings'
import { Route as BoxosAdminReportsRouteImport } from './routes/boxos-admin.reports'
import { Route as BoxosAdminActivityRouteImport } from './routes/boxos-admin.activity'
import { Route as AthleteSettingsRouteImport } from './routes/athlete.settings'
import { Route as AthleteScheduleRouteImport } from './routes/athlete.schedule'
import { Route as AthleteProfileRouteImport } from './routes/athlete.profile'
import { Route as AthletePaymentsRouteImport } from './routes/athlete.payments'
import { Route as AthleteNotificationsRouteImport } from './routes/athlete.notifications'
import { Route as AthleteDocumentsRouteImport } from './routes/athlete.documents'
import { Route as AthleteBoutsRouteImport } from './routes/athlete.bouts'
import { Route as AthleteAttendanceRouteImport } from './routes/athlete.attendance'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchedulingRouteImport } from './routes/admin.scheduling'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminJudgesRouteImport } from './routes/admin.judges'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminBoutsRouteImport } from './routes/admin.bouts'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAthletesRouteImport } from './routes/admin.athletes'
import { Route as BoxosAdminAcademiesAcademyIdRouteImport } from './routes/boxos-admin.academies.$academyId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxosAdminRoute = BoxosAdminRouteImport.update({
  id: '/boxos-admin',
  path: '/boxos-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteRoute = AthleteRouteImport.update({
  id: '/athlete',
  path: '/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const JudgeIndexRoute = JudgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JudgeRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const BoxosAdminIndexRoute = BoxosAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoxosAdminRoute,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AthleteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminReportsRoute = SuperadminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRefundsRoute = SuperadminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminNotificationsRoute = SuperadminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminJudgesRoute = SuperadminJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFeesRoute = SuperadminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDiscountsRoute = SuperadminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminConfigRoute = SuperadminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCoachesRoute = SuperadminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminClassAssigningRoute =
  SuperadminClassAssigningRouteImport.update({
    id: '/class-assigning',
    path: '/class-assigning',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminBoutsRoute = SuperadminBoutsRouteImport.update({
  id: '/bouts',
  path: '/bouts',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAttendanceRoute = SuperadminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAthletesRoute = SuperadminAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAdminsRoute = SuperadminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAcademiesRoute = SuperadminAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => SuperadminRoute,
} as any)
const JudgeExpiredRoute = JudgeExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => JudgeRoute,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoachRoute,
} as any)
const CoachNotificationsRoute = CoachNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CoachRoute,
} as any)
const CoachBoxersRoute = CoachBoxersRouteImport.update({
  id: '/boxers',
  path: '/boxers',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAttendanceRoute = CoachAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => CoachRoute,
} as any)
const BoxosAdminSettingsRoute = BoxosAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BoxosAdminRoute,
} as any)
const BoxosAdminReportsRoute = BoxosAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BoxosAdminRoute,
} as any)
const BoxosAdminActivityRoute = BoxosAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => BoxosAdminRoute,
} as any)
const AthleteSettingsRoute = AthleteSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteScheduleRoute = AthleteScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteProfileRoute = AthleteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AthleteRoute,
} as any)
const AthletePaymentsRoute = AthletePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteNotificationsRoute = AthleteNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteDocumentsRoute = AthleteDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteBoutsRoute = AthleteBoutsRouteImport.update({
  id: '/bouts',
  path: '/bouts',
  getParentRoute: () => AthleteRoute,
} as any)
const AthleteAttendanceRoute = AthleteAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AthleteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulingRoute = AdminSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJudgesRoute = AdminJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoutsRoute = AdminBoutsRouteImport.update({
  id: '/bouts',
  path: '/bouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAthletesRoute = AdminAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AdminRoute,
} as any)
const BoxosAdminAcademiesAcademyIdRoute =
  BoxosAdminAcademiesAcademyIdRouteImport.update({
    id: '/academies/$academyId',
    path: '/academies/$academyId',
    getParentRoute: () => BoxosAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/athlete': typeof AthleteRouteWithChildren
  '/boxos-admin': typeof BoxosAdminRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/bouts': typeof AdminBoutsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/athlete/attendance': typeof AthleteAttendanceRoute
  '/athlete/bouts': typeof AthleteBoutsRoute
  '/athlete/documents': typeof AthleteDocumentsRoute
  '/athlete/notifications': typeof AthleteNotificationsRoute
  '/athlete/payments': typeof AthletePaymentsRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/schedule': typeof AthleteScheduleRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/boxos-admin/activity': typeof BoxosAdminActivityRoute
  '/boxos-admin/reports': typeof BoxosAdminReportsRoute
  '/boxos-admin/settings': typeof BoxosAdminSettingsRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/coach/boxers': typeof CoachBoxersRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/judge/expired': typeof JudgeExpiredRoute
  '/superadmin/academies': typeof SuperadminAcademiesRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/athletes': typeof SuperadminAthletesRoute
  '/superadmin/attendance': typeof SuperadminAttendanceRoute
  '/superadmin/bouts': typeof SuperadminBoutsRoute
  '/superadmin/class-assigning': typeof SuperadminClassAssigningRoute
  '/superadmin/coaches': typeof SuperadminCoachesRoute
  '/superadmin/config': typeof SuperadminConfigRoute
  '/superadmin/discounts': typeof SuperadminDiscountsRoute
  '/superadmin/fees': typeof SuperadminFeesRoute
  '/superadmin/judges': typeof SuperadminJudgesRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/refunds': typeof SuperadminRefundsRoute
  '/superadmin/reports': typeof SuperadminReportsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/boxos-admin/': typeof BoxosAdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/judge/': typeof JudgeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/boxos-admin/academies/$academyId': typeof BoxosAdminAcademiesAcademyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/bouts': typeof AdminBoutsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/athlete/attendance': typeof AthleteAttendanceRoute
  '/athlete/bouts': typeof AthleteBoutsRoute
  '/athlete/documents': typeof AthleteDocumentsRoute
  '/athlete/notifications': typeof AthleteNotificationsRoute
  '/athlete/payments': typeof AthletePaymentsRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/schedule': typeof AthleteScheduleRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/boxos-admin/activity': typeof BoxosAdminActivityRoute
  '/boxos-admin/reports': typeof BoxosAdminReportsRoute
  '/boxos-admin/settings': typeof BoxosAdminSettingsRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/coach/boxers': typeof CoachBoxersRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/judge/expired': typeof JudgeExpiredRoute
  '/superadmin/academies': typeof SuperadminAcademiesRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/athletes': typeof SuperadminAthletesRoute
  '/superadmin/attendance': typeof SuperadminAttendanceRoute
  '/superadmin/bouts': typeof SuperadminBoutsRoute
  '/superadmin/class-assigning': typeof SuperadminClassAssigningRoute
  '/superadmin/coaches': typeof SuperadminCoachesRoute
  '/superadmin/config': typeof SuperadminConfigRoute
  '/superadmin/discounts': typeof SuperadminDiscountsRoute
  '/superadmin/fees': typeof SuperadminFeesRoute
  '/superadmin/judges': typeof SuperadminJudgesRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/refunds': typeof SuperadminRefundsRoute
  '/superadmin/reports': typeof SuperadminReportsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/boxos-admin': typeof BoxosAdminIndexRoute
  '/coach': typeof CoachIndexRoute
  '/judge': typeof JudgeIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/boxos-admin/academies/$academyId': typeof BoxosAdminAcademiesAcademyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/athlete': typeof AthleteRouteWithChildren
  '/boxos-admin': typeof BoxosAdminRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/bouts': typeof AdminBoutsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/athlete/attendance': typeof AthleteAttendanceRoute
  '/athlete/bouts': typeof AthleteBoutsRoute
  '/athlete/documents': typeof AthleteDocumentsRoute
  '/athlete/notifications': typeof AthleteNotificationsRoute
  '/athlete/payments': typeof AthletePaymentsRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/schedule': typeof AthleteScheduleRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/boxos-admin/activity': typeof BoxosAdminActivityRoute
  '/boxos-admin/reports': typeof BoxosAdminReportsRoute
  '/boxos-admin/settings': typeof BoxosAdminSettingsRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/coach/boxers': typeof CoachBoxersRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/judge/expired': typeof JudgeExpiredRoute
  '/superadmin/academies': typeof SuperadminAcademiesRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/athletes': typeof SuperadminAthletesRoute
  '/superadmin/attendance': typeof SuperadminAttendanceRoute
  '/superadmin/bouts': typeof SuperadminBoutsRoute
  '/superadmin/class-assigning': typeof SuperadminClassAssigningRoute
  '/superadmin/coaches': typeof SuperadminCoachesRoute
  '/superadmin/config': typeof SuperadminConfigRoute
  '/superadmin/discounts': typeof SuperadminDiscountsRoute
  '/superadmin/fees': typeof SuperadminFeesRoute
  '/superadmin/judges': typeof SuperadminJudgesRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/refunds': typeof SuperadminRefundsRoute
  '/superadmin/reports': typeof SuperadminReportsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/boxos-admin/': typeof BoxosAdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/judge/': typeof JudgeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/boxos-admin/academies/$academyId': typeof BoxosAdminAcademiesAcademyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/athlete'
    | '/boxos-admin'
    | '/coach'
    | '/judge'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/superadmin'
    | '/admin/athletes'
    | '/admin/attendance'
    | '/admin/bouts'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/judges'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/athlete/attendance'
    | '/athlete/bouts'
    | '/athlete/documents'
    | '/athlete/notifications'
    | '/athlete/payments'
    | '/athlete/profile'
    | '/athlete/schedule'
    | '/athlete/settings'
    | '/boxos-admin/activity'
    | '/boxos-admin/reports'
    | '/boxos-admin/settings'
    | '/coach/attendance'
    | '/coach/boxers'
    | '/coach/notifications'
    | '/coach/settings'
    | '/judge/expired'
    | '/superadmin/academies'
    | '/superadmin/admins'
    | '/superadmin/athletes'
    | '/superadmin/attendance'
    | '/superadmin/bouts'
    | '/superadmin/class-assigning'
    | '/superadmin/coaches'
    | '/superadmin/config'
    | '/superadmin/discounts'
    | '/superadmin/fees'
    | '/superadmin/judges'
    | '/superadmin/notifications'
    | '/superadmin/refunds'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/athlete/'
    | '/boxos-admin/'
    | '/coach/'
    | '/judge/'
    | '/superadmin/'
    | '/boxos-admin/academies/$academyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/athletes'
    | '/admin/attendance'
    | '/admin/bouts'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/judges'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/athlete/attendance'
    | '/athlete/bouts'
    | '/athlete/documents'
    | '/athlete/notifications'
    | '/athlete/payments'
    | '/athlete/profile'
    | '/athlete/schedule'
    | '/athlete/settings'
    | '/boxos-admin/activity'
    | '/boxos-admin/reports'
    | '/boxos-admin/settings'
    | '/coach/attendance'
    | '/coach/boxers'
    | '/coach/notifications'
    | '/coach/settings'
    | '/judge/expired'
    | '/superadmin/academies'
    | '/superadmin/admins'
    | '/superadmin/athletes'
    | '/superadmin/attendance'
    | '/superadmin/bouts'
    | '/superadmin/class-assigning'
    | '/superadmin/coaches'
    | '/superadmin/config'
    | '/superadmin/discounts'
    | '/superadmin/fees'
    | '/superadmin/judges'
    | '/superadmin/notifications'
    | '/superadmin/refunds'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin'
    | '/athlete'
    | '/boxos-admin'
    | '/coach'
    | '/judge'
    | '/superadmin'
    | '/boxos-admin/academies/$academyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/athlete'
    | '/boxos-admin'
    | '/coach'
    | '/judge'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/superadmin'
    | '/admin/athletes'
    | '/admin/attendance'
    | '/admin/bouts'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/judges'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/athlete/attendance'
    | '/athlete/bouts'
    | '/athlete/documents'
    | '/athlete/notifications'
    | '/athlete/payments'
    | '/athlete/profile'
    | '/athlete/schedule'
    | '/athlete/settings'
    | '/boxos-admin/activity'
    | '/boxos-admin/reports'
    | '/boxos-admin/settings'
    | '/coach/attendance'
    | '/coach/boxers'
    | '/coach/notifications'
    | '/coach/settings'
    | '/judge/expired'
    | '/superadmin/academies'
    | '/superadmin/admins'
    | '/superadmin/athletes'
    | '/superadmin/attendance'
    | '/superadmin/bouts'
    | '/superadmin/class-assigning'
    | '/superadmin/coaches'
    | '/superadmin/config'
    | '/superadmin/discounts'
    | '/superadmin/fees'
    | '/superadmin/judges'
    | '/superadmin/notifications'
    | '/superadmin/refunds'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/athlete/'
    | '/boxos-admin/'
    | '/coach/'
    | '/judge/'
    | '/superadmin/'
    | '/boxos-admin/academies/$academyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AthleteRoute: typeof AthleteRouteWithChildren
  BoxosAdminRoute: typeof BoxosAdminRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  JudgeRoute: typeof JudgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxos-admin': {
      id: '/boxos-admin'
      path: '/boxos-admin'
      fullPath: '/boxos-admin'
      preLoaderRoute: typeof BoxosAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete': {
      id: '/athlete'
      path: '/athlete'
      fullPath: '/athlete'
      preLoaderRoute: typeof AthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/judge/': {
      id: '/judge/'
      path: '/'
      fullPath: '/judge/'
      preLoaderRoute: typeof JudgeIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/boxos-admin/': {
      id: '/boxos-admin/'
      path: '/'
      fullPath: '/boxos-admin/'
      preLoaderRoute: typeof BoxosAdminIndexRouteImport
      parentRoute: typeof BoxosAdminRoute
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/reports': {
      id: '/superadmin/reports'
      path: '/reports'
      fullPath: '/superadmin/reports'
      preLoaderRoute: typeof SuperadminReportsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/refunds': {
      id: '/superadmin/refunds'
      path: '/refunds'
      fullPath: '/superadmin/refunds'
      preLoaderRoute: typeof SuperadminRefundsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/notifications': {
      id: '/superadmin/notifications'
      path: '/notifications'
      fullPath: '/superadmin/notifications'
      preLoaderRoute: typeof SuperadminNotificationsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/judges': {
      id: '/superadmin/judges'
      path: '/judges'
      fullPath: '/superadmin/judges'
      preLoaderRoute: typeof SuperadminJudgesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/fees': {
      id: '/superadmin/fees'
      path: '/fees'
      fullPath: '/superadmin/fees'
      preLoaderRoute: typeof SuperadminFeesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/discounts': {
      id: '/superadmin/discounts'
      path: '/discounts'
      fullPath: '/superadmin/discounts'
      preLoaderRoute: typeof SuperadminDiscountsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/config': {
      id: '/superadmin/config'
      path: '/config'
      fullPath: '/superadmin/config'
      preLoaderRoute: typeof SuperadminConfigRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/coaches': {
      id: '/superadmin/coaches'
      path: '/coaches'
      fullPath: '/superadmin/coaches'
      preLoaderRoute: typeof SuperadminCoachesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/class-assigning': {
      id: '/superadmin/class-assigning'
      path: '/class-assigning'
      fullPath: '/superadmin/class-assigning'
      preLoaderRoute: typeof SuperadminClassAssigningRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/bouts': {
      id: '/superadmin/bouts'
      path: '/bouts'
      fullPath: '/superadmin/bouts'
      preLoaderRoute: typeof SuperadminBoutsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/attendance': {
      id: '/superadmin/attendance'
      path: '/attendance'
      fullPath: '/superadmin/attendance'
      preLoaderRoute: typeof SuperadminAttendanceRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/athletes': {
      id: '/superadmin/athletes'
      path: '/athletes'
      fullPath: '/superadmin/athletes'
      preLoaderRoute: typeof SuperadminAthletesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/admins': {
      id: '/superadmin/admins'
      path: '/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof SuperadminAdminsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/academies': {
      id: '/superadmin/academies'
      path: '/academies'
      fullPath: '/superadmin/academies'
      preLoaderRoute: typeof SuperadminAcademiesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/judge/expired': {
      id: '/judge/expired'
      path: '/expired'
      fullPath: '/judge/expired'
      preLoaderRoute: typeof JudgeExpiredRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/coach/settings': {
      id: '/coach/settings'
      path: '/settings'
      fullPath: '/coach/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/notifications': {
      id: '/coach/notifications'
      path: '/notifications'
      fullPath: '/coach/notifications'
      preLoaderRoute: typeof CoachNotificationsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/boxers': {
      id: '/coach/boxers'
      path: '/boxers'
      fullPath: '/coach/boxers'
      preLoaderRoute: typeof CoachBoxersRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/attendance': {
      id: '/coach/attendance'
      path: '/attendance'
      fullPath: '/coach/attendance'
      preLoaderRoute: typeof CoachAttendanceRouteImport
      parentRoute: typeof CoachRoute
    }
    '/boxos-admin/settings': {
      id: '/boxos-admin/settings'
      path: '/settings'
      fullPath: '/boxos-admin/settings'
      preLoaderRoute: typeof BoxosAdminSettingsRouteImport
      parentRoute: typeof BoxosAdminRoute
    }
    '/boxos-admin/reports': {
      id: '/boxos-admin/reports'
      path: '/reports'
      fullPath: '/boxos-admin/reports'
      preLoaderRoute: typeof BoxosAdminReportsRouteImport
      parentRoute: typeof BoxosAdminRoute
    }
    '/boxos-admin/activity': {
      id: '/boxos-admin/activity'
      path: '/activity'
      fullPath: '/boxos-admin/activity'
      preLoaderRoute: typeof BoxosAdminActivityRouteImport
      parentRoute: typeof BoxosAdminRoute
    }
    '/athlete/settings': {
      id: '/athlete/settings'
      path: '/settings'
      fullPath: '/athlete/settings'
      preLoaderRoute: typeof AthleteSettingsRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/schedule': {
      id: '/athlete/schedule'
      path: '/schedule'
      fullPath: '/athlete/schedule'
      preLoaderRoute: typeof AthleteScheduleRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/profile': {
      id: '/athlete/profile'
      path: '/profile'
      fullPath: '/athlete/profile'
      preLoaderRoute: typeof AthleteProfileRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/payments': {
      id: '/athlete/payments'
      path: '/payments'
      fullPath: '/athlete/payments'
      preLoaderRoute: typeof AthletePaymentsRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/notifications': {
      id: '/athlete/notifications'
      path: '/notifications'
      fullPath: '/athlete/notifications'
      preLoaderRoute: typeof AthleteNotificationsRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/documents': {
      id: '/athlete/documents'
      path: '/documents'
      fullPath: '/athlete/documents'
      preLoaderRoute: typeof AthleteDocumentsRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/bouts': {
      id: '/athlete/bouts'
      path: '/bouts'
      fullPath: '/athlete/bouts'
      preLoaderRoute: typeof AthleteBoutsRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athlete/attendance': {
      id: '/athlete/attendance'
      path: '/attendance'
      fullPath: '/athlete/attendance'
      preLoaderRoute: typeof AthleteAttendanceRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling': {
      id: '/admin/scheduling'
      path: '/scheduling'
      fullPath: '/admin/scheduling'
      preLoaderRoute: typeof AdminSchedulingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/judges': {
      id: '/admin/judges'
      path: '/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AdminJudgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bouts': {
      id: '/admin/bouts'
      path: '/bouts'
      fullPath: '/admin/bouts'
      preLoaderRoute: typeof AdminBoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/athletes': {
      id: '/admin/athletes'
      path: '/athletes'
      fullPath: '/admin/athletes'
      preLoaderRoute: typeof AdminAthletesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/boxos-admin/academies/$academyId': {
      id: '/boxos-admin/academies/$academyId'
      path: '/academies/$academyId'
      fullPath: '/boxos-admin/academies/$academyId'
      preLoaderRoute: typeof BoxosAdminAcademiesAcademyIdRouteImport
      parentRoute: typeof BoxosAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAthletesRoute: typeof AdminAthletesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBoutsRoute: typeof AdminBoutsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminJudgesRoute: typeof AdminJudgesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchedulingRoute: typeof AdminSchedulingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAthletesRoute: AdminAthletesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBoutsRoute: AdminBoutsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminJudgesRoute: AdminJudgesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchedulingRoute: AdminSchedulingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AthleteRouteChildren {
  AthleteAttendanceRoute: typeof AthleteAttendanceRoute
  AthleteBoutsRoute: typeof AthleteBoutsRoute
  AthleteDocumentsRoute: typeof AthleteDocumentsRoute
  AthleteNotificationsRoute: typeof AthleteNotificationsRoute
  AthletePaymentsRoute: typeof AthletePaymentsRoute
  AthleteProfileRoute: typeof AthleteProfileRoute
  AthleteScheduleRoute: typeof AthleteScheduleRoute
  AthleteSettingsRoute: typeof AthleteSettingsRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
}

const AthleteRouteChildren: AthleteRouteChildren = {
  AthleteAttendanceRoute: AthleteAttendanceRoute,
  AthleteBoutsRoute: AthleteBoutsRoute,
  AthleteDocumentsRoute: AthleteDocumentsRoute,
  AthleteNotificationsRoute: AthleteNotificationsRoute,
  AthletePaymentsRoute: AthletePaymentsRoute,
  AthleteProfileRoute: AthleteProfileRoute,
  AthleteScheduleRoute: AthleteScheduleRoute,
  AthleteSettingsRoute: AthleteSettingsRoute,
  AthleteIndexRoute: AthleteIndexRoute,
}

const AthleteRouteWithChildren =
  AthleteRoute._addFileChildren(AthleteRouteChildren)

interface BoxosAdminRouteChildren {
  BoxosAdminActivityRoute: typeof BoxosAdminActivityRoute
  BoxosAdminReportsRoute: typeof BoxosAdminReportsRoute
  BoxosAdminSettingsRoute: typeof BoxosAdminSettingsRoute
  BoxosAdminIndexRoute: typeof BoxosAdminIndexRoute
  BoxosAdminAcademiesAcademyIdRoute: typeof BoxosAdminAcademiesAcademyIdRoute
}

const BoxosAdminRouteChildren: BoxosAdminRouteChildren = {
  BoxosAdminActivityRoute: BoxosAdminActivityRoute,
  BoxosAdminReportsRoute: BoxosAdminReportsRoute,
  BoxosAdminSettingsRoute: BoxosAdminSettingsRoute,
  BoxosAdminIndexRoute: BoxosAdminIndexRoute,
  BoxosAdminAcademiesAcademyIdRoute: BoxosAdminAcademiesAcademyIdRoute,
}

const BoxosAdminRouteWithChildren = BoxosAdminRoute._addFileChildren(
  BoxosAdminRouteChildren,
)

interface CoachRouteChildren {
  CoachAttendanceRoute: typeof CoachAttendanceRoute
  CoachBoxersRoute: typeof CoachBoxersRoute
  CoachNotificationsRoute: typeof CoachNotificationsRoute
  CoachSettingsRoute: typeof CoachSettingsRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAttendanceRoute: CoachAttendanceRoute,
  CoachBoxersRoute: CoachBoxersRoute,
  CoachNotificationsRoute: CoachNotificationsRoute,
  CoachSettingsRoute: CoachSettingsRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface JudgeRouteChildren {
  JudgeExpiredRoute: typeof JudgeExpiredRoute
  JudgeIndexRoute: typeof JudgeIndexRoute
}

const JudgeRouteChildren: JudgeRouteChildren = {
  JudgeExpiredRoute: JudgeExpiredRoute,
  JudgeIndexRoute: JudgeIndexRoute,
}

const JudgeRouteWithChildren = JudgeRoute._addFileChildren(JudgeRouteChildren)

interface SuperadminRouteChildren {
  SuperadminAcademiesRoute: typeof SuperadminAcademiesRoute
  SuperadminAdminsRoute: typeof SuperadminAdminsRoute
  SuperadminAthletesRoute: typeof SuperadminAthletesRoute
  SuperadminAttendanceRoute: typeof SuperadminAttendanceRoute
  SuperadminBoutsRoute: typeof SuperadminBoutsRoute
  SuperadminClassAssigningRoute: typeof SuperadminClassAssigningRoute
  SuperadminCoachesRoute: typeof SuperadminCoachesRoute
  SuperadminConfigRoute: typeof SuperadminConfigRoute
  SuperadminDiscountsRoute: typeof SuperadminDiscountsRoute
  SuperadminFeesRoute: typeof SuperadminFeesRoute
  SuperadminJudgesRoute: typeof SuperadminJudgesRoute
  SuperadminNotificationsRoute: typeof SuperadminNotificationsRoute
  SuperadminRefundsRoute: typeof SuperadminRefundsRoute
  SuperadminReportsRoute: typeof SuperadminReportsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAcademiesRoute: SuperadminAcademiesRoute,
  SuperadminAdminsRoute: SuperadminAdminsRoute,
  SuperadminAthletesRoute: SuperadminAthletesRoute,
  SuperadminAttendanceRoute: SuperadminAttendanceRoute,
  SuperadminBoutsRoute: SuperadminBoutsRoute,
  SuperadminClassAssigningRoute: SuperadminClassAssigningRoute,
  SuperadminCoachesRoute: SuperadminCoachesRoute,
  SuperadminConfigRoute: SuperadminConfigRoute,
  SuperadminDiscountsRoute: SuperadminDiscountsRoute,
  SuperadminFeesRoute: SuperadminFeesRoute,
  SuperadminJudgesRoute: SuperadminJudgesRoute,
  SuperadminNotificationsRoute: SuperadminNotificationsRoute,
  SuperadminRefundsRoute: SuperadminRefundsRoute,
  SuperadminReportsRoute: SuperadminReportsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AthleteRoute: AthleteRouteWithChildren,
  BoxosAdminRoute: BoxosAdminRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  JudgeRoute: JudgeRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
